version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-backend
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatbot
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: chatbot-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
